import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Cupra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://db.onlinewebfonts.com/c/1a998736e1a95af302b555d9cf0f552b?family=Cupra"
          rel="stylesheet"
        />
        <link
          href="https://db.onlinewebfonts.com/c/d8c243c0372d796c35aac398a8e882a1?family=Cupra+Light"
          rel="stylesheet"
          type="text/css"
        />
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
